project_id = "mzsdddminwqgfegxotza"

[functions.delete-user]
verify_jwt = true

[functions.create-gerente]
verify_jwt = true

[functions.create-admin]
verify_jwt = true

[functions.update-admin]
verify_jwt = true

[functions.list-admins]
verify_jwt = true

[functions.check-admin-exists]
verify_jwt = false

[functions.create-first-admin]
verify_jwt = false

[functions.get-email-by-username]
verify_jwt = false

[functions.send-report]
verify_jwt = true

[functions.send-whatsapp-report]
verify_jwt = true

[functions.send-changelog-email]
verify_jwt = true
