project_id = "mzsdddminwqgfegxotza"

[functions.delete-user]
verify_jwt = true

[functions.create-gerente]
verify_jwt = true

[functions.create-admin]
verify_jwt = true

[functions.update-admin]
verify_jwt = true

[functions.list-admins]
verify_jwt = true

[functions.check-admin-exists]
verify_jwt = false

[functions.create-first-admin]
verify_jwt = false

[functions.get-email-by-username]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.send-whatsapp-report]
verify_jwt = false

[functions.send-changelog-email]
verify_jwt = true

[functions.list-users-for-email]
verify_jwt = true

[functions.check-manual-reports]
verify_jwt = false

[functions.send-whatsapp-cobranca]
verify_jwt = true

[functions.check-pending-lancamentos]
verify_jwt = false

[functions.check-whatsapp-reports]
verify_jwt = false

[functions.receive-whatsapp-webhook]
verify_jwt = false
